mod 'puppetlabs/stdlib'
mod 'puppetlabs/transition'
mod 'puppetlabs/inifile'
mod 'puppetlabs/puppet_agent'
mod 'puppetlabs/apt'
mod 'mysql', :git => 'git@github.com:abottchen/puppetlabs-mysql.git'
mod 'common', :git => 'https://github.com/abottchen/sw_repo.git', :install_path => 'modules/hieradata'
mod 'envrepo', :git => 'https://github.com/abottchen/env_repo.git'
